version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build: .
    container_name: backend-server
    restart: always
    ports:
      - '3004:3004'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo-data:
